// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAThZnQ4mOykeLsSkFuwG-zXVMwfei0AM4',
    appId: '1:399645935240:web:5688425b57ece367a1c13d',
    messagingSenderId: '399645935240',
    projectId: 'koutix-57444',
    authDomain: 'koutix-57444.firebaseapp.com',
    storageBucket: 'koutix-57444.firebasestorage.app',
    measurementId: 'G-KQG6G2VSF7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJkB-mDgl-T3sMvjVeorq2TX6aIroX8cE',
    appId: '1:399645935240:android:2a8cd8582ce1a526a1c13d',
    messagingSenderId: '399645935240',
    projectId: 'koutix-57444',
    storageBucket: 'koutix-57444.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa0lhRP6uAaJ0iYgT0fgPDpr8Tv-zxf3Y',
    appId: '1:399645935240:ios:30ba56cc7dd26af6a1c13d',
    messagingSenderId: '399645935240',
    projectId: 'koutix-57444',
    storageBucket: 'koutix-57444.firebasestorage.app',
    iosBundleId: 'com.example.koutixApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa0lhRP6uAaJ0iYgT0fgPDpr8Tv-zxf3Y',
    appId: '1:399645935240:ios:30ba56cc7dd26af6a1c13d',
    messagingSenderId: '399645935240',
    projectId: 'koutix-57444',
    storageBucket: 'koutix-57444.firebasestorage.app',
    iosBundleId: 'com.example.koutixApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAThZnQ4mOykeLsSkFuwG-zXVMwfei0AM4',
    appId: '1:399645935240:web:0ed2ebd915696014a1c13d',
    messagingSenderId: '399645935240',
    projectId: 'koutix-57444',
    authDomain: 'koutix-57444.firebaseapp.com',
    storageBucket: 'koutix-57444.firebasestorage.app',
    measurementId: 'G-JFD2YQCVRM',
  );
}
